apiVersion: v1
kind: Service
metadata:
  name: {{ template "wp.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.wp.service.type }}
  ports:
  - name: http
    port: {{ .Values.wp.service.port }}
    targetPort: http
    protocol: TCP
  selector:
    {{- include "wp.selectorLabels" . | nindent 4 }}